### ISSUE TITLE
Game crashes upon spawning vehicles (FiveM)

### ISSUE THREAD

**Issue by jessicathelesbian** [MAFINS/MenyooSP#626]
Hello, im trying to use GTA V mods again but have the exact same issues I had about a year ago. For some reason whenever I try spawning a vehicle my game just crashes and displays the error message that will be displayed at the end of this comment. I hope I might be able to fix this cause nothing has ever worked. 
[Window Title]
FiveM

[Main Instruction]
An exception occurred executing native 0xa670b3662faffbd0 in a ViSH plugin (0x7ff88c24d93d - adhesive.dll+2D2D93D). The game has been terminated.

[Content]
 

[^] Hide details  [Save information] [Close]

[Expanded Information]
Report ID: si-ba291088ab6a4863bba082f232e4eff5
You can press Ctrl-C to copy this message and paste it elsewhere.

**Comment by The-UnXplained** [comment]
This official version of the menu hasn't been updated for some time now, hence why it will not work / or fully work correctly. I suggest you search for my version thats always fully up-to-date and try that. (Link on profile)

**Comment by AmazyCrazy** [comment]
@The-UnXplained I tried your version of Menyoo and for me it's broken when I change to mp female and then try to change clothing it just freezes and then eventually crashes? Any solutions?

Thanks :)

**Comment by vbelevcev** [comment]
> @The-UnXplainedЯ попробовал вашу версию Menyoo, и для меня она не работает, когда я перехожу на женский mp, а затем пытаюсь сменить одежду, она просто зависает, а затем в конце концов вылетает? Есть решения? У меня последняя версия игры
> 
> Спасибо :)

Try my github, I make a version purely for myself, I am Russian there is russified a lot of things, as a temporary solution, maybe it will help you, I do not remember what I fixed.

**Comment by The-UnXplained** [comment]
[vbelevcev] - pmsl, i doubt you have fixed anything yourself. It wasn't so long ago you was begging me to show you my version's source code and when i told you part of my updated 'GTAmemory' file you still didn't have a clue. 

@AmazyCrazy Thanks for making me aware of this, to be honest, i'm not sure at present what's causing the issue. I will have to look into it whenever i get time.

**Comment by vbelevcev** [comment]
> [vbelevcev] - pmsl, i doubt you have fixed anything yourself. It wasn't so long ago you was begging me to show you my version's source code and when i told you part of my updated 'GTAmemory' file you still didn't have a clue.
> 
> @AmazyCrazy Thanks for making me aware of this, to be honest, i'm not sure at present what's causing the issue. I will have to look into it whenever i get time.

Clearly you don't know what your doing..

**Comment by The-UnXplained** [comment]
@vbelevcev sorry to disappoint you, but i don't take screenshots of rambling, childish comments by people like you. Since you act like you know everything, and have supposedly fixed everything yourself, you won't mind becoming another one of mafins lapdogs and submitting some pull request on here then..?

**Comment by The-UnXplained** [comment]
> @The-UnXplained I tried your version of Menyoo and for me it's broken when I change to mp female and then try to change clothing it just freezes and then eventually crashes? Any solutions? I'm on the latest game version
> 
> Thanks :)

I have looked into this issue, and i think its because of when rockstar added placeholders in the game files for the E&E content some time ago that was/is causing the issue but i could be wrong!. I have made some changes to my version, it's still not great at the moment, but its not freezing & crashing instantly now.

**Comment by vbelevcev** [comment]
> @vbelevcev sorry to disappoint you, but i don't take screenshots of rambling, childish comments by people like you. Since you act like you know everything, and have supposedly fixed everything yourself, you won't mind becoming another one of mafins lapdogs and submitting some pull request on here then..?

 You puppy, go back to the booth, get lost and yapping there, and come out when the owner allows, if you dare to say something, bring proof, or don't be impertinent, and keep yapping, so puppy, I have all the data on you, you are nobody and your name is nothing, and your version of the miner is of no fucking interest to anyone, I won't give you a code, don't even try.
